### ISSUE TITLE
Reconsider valve method once diffusion data is required

### ISSUE THREAD

**Issue by reidaaron** [reidaaron/FYDP#9]
Need to decide whether to start at vacuum or atmospheric pressure. Currently assumes 0 atmg at start and release pressure for valve is specified at gauge. Need to make sure units are consistent.

**Comment by drgroot** [comment]
Blocked
https://github.com/reidaaron/FYDP/issues/7

**Comment by drgroot** [comment]
Also took a look at the valve code to see why its goes to zero for pressure in headspace, its not.

It reaches the closing pressure
